version: '3.4'

services:
  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: GatewayApi/Dockerfile

  catalogo:
    image: ${DOCKER_REGISTRY-}catalogo
    build:
      context: .
      dockerfile: Catalogo/Dockerfile


  pedidos:
    image: ${DOCKER_REGISTRY-}pedidos
    build:
      context: .
      dockerfile: Pedidos/Dockerfile

